In [ ]:
1. What is a Python library? Why to we use Python libraries?

In [ ]:
Ans python library as a name telling  alibrary of python it have   inbulit founction ,code which make work easier for programmer reduce the complexity of code
all the founction and class are reusable and  easy to code


In [ ]:
2.What is the difference between Numpy array and  List?

In [ ]:
Ans: 
Numpy array:
1. it  have dynamic memeory allocation
2. it is built on c++
3. it is fast
4. A  numpy array are homogeneous data structure

List:
1. it have contegeous  memeory allocation 
2. it is  not built on c++
3. it is slow
4. A list is hetrogeneous data structure

In [ ]:
3. Find  the shape, size and  dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
             [9, 10, 11, 12]])
print(np.size(arr))
print(np.shape(arr))
print(np.ndim(arr))

12
(3, 4)
2


In [ ]:

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [12]:
import numpy as np
a=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
a[0]

array([1, 2, 3, 4])

In [ ]:
5. How do you access the element at the third row and  fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [20]:
import numpy as np
a=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
a[2,3]

12

In [ ]:
6. Write code to extract all odd -indexed  elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np
a=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
a[:,1::2]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
7. How can you generate a ranDom 3x3 matrix with values between 0 and 1?

In [12]:
import numpy as np
np.random.rand(3,3)



array([[0.79134068, 0.29871025, 0.2662529 ],
       [0.66571205, 0.44389398, 0.62626543],
       [0.2693174 , 0.44485942, 0.55155839]])

In [ ]:
8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
np.random.rand:
    It give us  random  number from uniform distribution over the distribution [0,1)
np.random.randn:
    It give us random number from normal distribution                                                                             
                                                   

In [ ]:
9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
import numpy as np 
a=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
a2=np.expand_dims(a,axis=0)
a2


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
10.10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
import numpy as np 
a=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

k=a.T
k

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [ ]:
Perform the following operation using Python
1.Index wise multiplication
2. Matrix multiplication
3.Add both the matrix
4.Subtract matrix B from a
5.Divide Matrix B by A


In [43]:
import numpy as np 
A1=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
B2=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [44]:
A1*B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [45]:
A1 @ B2.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [46]:
A1+B2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [47]:
A1-B2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
B2/A1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
12.  Which function in Numpy can be useD to swap the byte orDer of an array?

In [ ]:
np.ndarray.byteswap() this founction swap the byte order of an array without chaanging 
memory layout of an arrau

In [ ]:
 13.What is the significance of the np.linalg.inv function?

In [ ]:
Ans:this founction in numpy used for calculating the multiplicative inverse of a squre matrix
this founctionn is used for the finding the determinant,Solving Systems of Linear Equations,Numerical Stability

In [ ]:
14.What does the np.reshape function do, and how is it used?

In [ ]:
ans : We change the size of an array we reshape it again according to our want  array remain orignal no change in data,
Its's alo used to convert onedimensional array into multi dimensional array
Contiguous Memory:Reshaping does not alter the underlying data of the array

In [ ]:
15. What is broadcasting in Numpy?

In [ ]:
Broadcasting refers to  implicit and  automatic allignment of an array into diffrent shapes dutring arhtmetic operation
